# Generated by Django 2.0.3 on 2018-03-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_auto_20180314_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 Artist ID'),
        ),
    ]
