# Generated by Django 2.0.3 on 2018-03-26 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_auto_20180325_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistlike',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user_info_list', to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='artistlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_artist_info_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
